### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by pzybe** [rome-user/pulumi-stack-example#1]
have you kept up with using Clojure+Pulumi or has it worked out well for you in practice? I like your example, and was considering making the attempt as well.  I work with Java devs, and don't enjoy having to write IAC in python/typescript.

sorry to bother, I know this isn't a real issue.

**Comment by rome-user** [comment]
Hello,

I was interested in Pulumi at one time. I saw discussion of people wanting custom bindings for Kotlin and Scala. There was someone asking a question about Clojure. So made this example and uploaded to GitHub. However, due to limitations of the free tier, I decided to not continue using Pulumi.

There is a minor problem in my example, in that the Maven plugins are configured in the `pom.xml`, even though you can configure them from Leningen `project.clj`. Maybe it's a good idea to update this, so that people do not have to figure this out themselves.
